- name: Disable SELinux
  selinux:
    state: disabled

- name: Copy kibana repo
  copy:
    src: ./setup-kibana/files/kibana.repo
    dest: /etc/yum.repos.d/kibana.repo
    mode: '0644'

- name: Install epel-release, lsof
  yum: 
    state: present
    name: 
      - epel-release
      - lsof

- name: Install kibana, nginx
  yum: 
    state: present
    name: 
      - kibana
      - nginx

- name: Generate /etc/hosts from template
  template:
    src: ./setup-kibana/templates/hosts.j2
    dest: /etc/hosts
    mode: '0644'
  
- name: Generate kibana.conf for nginx from template
  template:
    src: ./setup-kibana/templates/kibana.conf.j2
    dest: /etc/nginx/conf.d/kibana.conf
    mode: '0644'

- name: Change default configs for nginx
  template:
    src: ./setup-kibana/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Generate kibana.yml
  template:
    src: ./setup-kibana/templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: '0660'

- name: Install oauth2-proxy 
  get_url:
    url: https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v6.1.1/oauth2-proxy-v6.1.1.linux-amd64.tar.gz
    dest: /tmp
  register: archive

- name: Unarchive oauth2-proxy 
  unarchive:
    src: /tmp/oauth2-proxy-v6.1.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
  when: archive.changed

- name: Get sha256sum checksum
  get_url:
    url: https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v6.1.1/oauth2-proxy-v6.1.1.linux-amd64-sha256sum.txt
    dest: /tmp
  when: archive.changed

- name: Validate oauth2-proxy binary 
  shell: sha256sum -c oauth2-proxy-v6.1.1.linux-amd64-sha256sum.txt 2>&1 | grep OK
  args:
    chdir: /tmp
  when: archive.changed

- name: Start and enable kibana
  systemd: 
     name: kibana
     state: started 
     enabled: yes

- name: Start and enable nginx
  systemd: 
     name: nginx
     state: started 
     enabled: yes

- name: Kill oauth2-proxy proccess if exists
  shell: kill -9 $(lsof -t -i:80)
  ignore_errors: yes

- name: Start oauth2-proxy
  shell: |
    nohup ./oauth2-proxy \
    --email-domain="gmail.com" \
    --http-address=":80" \
    --upstream="http://localhost:8080/" \
    --approval-prompt="auto" \
    --redirect-url="http://milan-elk.support-coe.com:80/oauth2/callback" \
    --provider=github \
    --cookie-secret="{{ my_cookie_secret }}" \
    --cookie-name="_oauth2_proxy" \
    --cookie-secure=false \
    --client-id="{{ my_github_id }}" \
    --client-secret="{{ my_github_secret }}" </dev/null >/dev/null 2>&1 &
  args:
    chdir: /tmp/oauth2-proxy-v6.1.1.linux-amd64
