- name: elasticsearch setup
  hosts: elasticsearch 
  become: yes
  tasks:
    - include_role:
        name: setup-elasticsearch
        tasks_from: main

- name: kibana setup
  hosts: kibana 
  become: yes
  tasks:
    - include_role:
        name: setup-kibana
        tasks_from: main
      vars:
        my_cookie_secret: "{{ cookie_secret }}"
        my_github_id: "{{ github_id }}"
        my_github_secret: "{{ github_secret }}"

- name: logstash setup
  hosts: logstash 
  become: yes
  tasks:
    - include_role:
        name: setup-logstash
        tasks_from: main